### ISSUE TITLE
min value of adaptiveHeight of description is not actual used

### ISSUE THREAD

**Issue by jcppkkk** [Undev/redmine_simple#4]
hi @nodecarter 
https://github.com/Undev/redmine_simple/blob/master/assets/javascripts/simplify_description.js#L1
When adjusting description text area, the min parameter in adaptiveHeight seems not actually setting minimal height. What's the intention of function adaptiveHeight ?

**Comment by nodecarter** [comment]
Hi @jcppkkk 
Without this adjustment the height of description textarea in simple mode can be too big or too small. http://goo.gl/lHGl1L

**Comment by jcppkkk** [comment]
However it resizes my description's height to one line height:
![image](https://cloud.githubusercontent.com/assets/84070/8204002/3272b0d2-1518-11e5-8317-88a95423570c.png)
I think the flow in original code will 
- Do nothing if height is smaller than min height
- Resize height to one line height if 
    - $(a).height() > min
    - No content when create new issue (scrollHeight = one line height)

So i decide to modify code. The result is following image
![image](https://cloud.githubusercontent.com/assets/84070/8204171/4fb68604-1519-11e5-832e-b15ea8f33b9a.png)

```diff
diff --git a/assets/javascripts/simplify_description.js b/assets/javascripts/simplify_description.js
index d4e15c2..a6e416e 100644
--- a/assets/javascripts/simplify_description.js
+++ b/assets/javascripts/simplify_description.js
@@ -1,11 +1,11 @@
 function adaptiveHeight(a, min, max) {
-  if ($(a).height() > min) {
-    $(a).height(0);
-    var newHeight = Math.min($(a)[0].scrollHeight, max);
-    $(a).height(newHeight);
-    if (parseInt(a.style.height) > $(window).height() - 30) {
-      $(document).scrollTop(parseInt(a.style.height));
-    }
+  scrollHeight = $(a)[0].scrollHeight
+  if (scrollHeight < min) {
+    $(a).height(min);
+  } else if(scrollHeight > max) {
+    $(a).height(max);
+  } else {
+    $(a).height(scrollHeight);
   }
 }
```

**Comment by nodecarter** [comment]
Thanks @jcppkkk. I have fixed too small height bug.
